version: 2

sources:
  - name: salesforce_raw_data
    schema: salesforce_raw_data
    tables:
      - name: Impact_Dashboard_Data_Form__c
        identifier: Impact_Dashboard_Data_Form__c
        description: Form data from the Impact Dashboard Data Form custom object in Salesforce.

      - name: Platform_Name__c
        identifier: Platform_Name__c
        description: Platform name data from the Platform Name custom object in Salesforce.

      - name: Policy_Name__c
        identifier: Policy_Name__c
        description: Policy name data from the Policy Name custom object in Salesforce.

      - name: Account
        identifier: Account
        description: Account data from the Account custom object in Salesforce.

      - name: Contact
        identifier: Contact
        description: Contact data from the Contact custom object in Salesforce.

  - name: GSheet_Raw_Data
    schema: GSheet_Raw_Data
    tables:
      - name: FX_Rates
        identifier: FX_Rates
        description: FX rate data for 2014 - present.
      - name: hist_FinalSheet
        identifier: hist_FinalSheet
        description: Aggregated Historical impact data from 2024 - 2025 Q2.
      - name: ref
        identifier: ref
        description: reference table of impact-particular-value label-title mapping. This is used to map current SF data to corresponding get title for each row, as per historical data's format.